### ISSUE TITLE
not able to install

### ISSUE THREAD

**Issue by dojje** [XtremeDevX/turbo-delete#1]
I am not able to install even though i did the steps in the readme.md file.

1. I opened powershell as administrator
2. I ran `Set-ExecutionPolicy RemoteSigned`
3. I answerd with `Y` on the prompt.
4. I ran `iwr -useb cdn.xtremedevx.com/turbo-delete/install.ps1 | iex`
5. A blue box came up on the top saying `Downloading Turbo Delete v0.0.1 from CDN` and `Connecting`
6. Then i got an error in red text
```
Start-BitsTransfer : HTTP-status 404: The requested url does not exist on the server.
At line:4 char:1
+ Start-BitsTransfer 'https://cdn.xtremedevx.com/Turbo-Delete.exe' "${E ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-BitsTransfer], Exception
    + FullyQualifiedErrorId : StartBitsTransferCOMException,Microsoft.BackgroundIntelligentTransfer.Management.NewBits
   TransferCommand
```

I don't really know how the installer works...

Is there perhaps another way to install this program?

**Comment by suptejas** [comment]
@Dojje 

The issue should be sorted out now 🙂. Please do let me know if you face any further issues, I'm happy to help!

**Comment by dojje** [comment]
It works now, thank you
