### ISSUE TITLE
ERROR  IO error for operation on TESTDIRTOBLAST: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by omac777** [XtremeDevX/turbo-delete#2]
TESTDIRTOBLAST was removed successfully, but it did display the above error.

```
ERROR  IO error for operation on TESTDIRTOBLAST: No such file or directory (os error 2)
```

I can't surface/repeat the scenario to bring up the error again easily, but the scenario was similar to this:

```
cd TESTDIRTOBLAST
ftzz g TESTA -n 10K -b 1M
ftzz g TESTB -n 10K -b 1M
ftzz g TESTC -n 10K -b 1M
ftzz g TESTD -n 10K -b 1M
cd ..
turbo-delete TESTDIRTOBLAST
```

I'm sorry I can't be more specific.

By the way, excellent work.  Congrats to you.

**Comment by rumia-san** [comment]
It seems that I have met the same problem, and I could reproduce this issue consistently.
I will try to do some investigation.
![ ERROR  IO error for operation](https://user-images.githubusercontent.com/51704722/162555008-51982684-002e-4c40-97f1-c66a8c895c15.png)

**Comment by rumia-san** [comment]
In my case, my test folder has been deleted by the following lines.

https://github.com/XtremeDevX/turbo-delete/blob/0.0.1/src/main.rs#L91-L105

**It seems that after the function call** `handle.await_complete();`, **the threads were exetuted and the folders has been already deleted.**

However, the following lines https://github.com/XtremeDevX/turbo-delete/blob/0.0.1/src/main.rs#L108-L135 **still tried to access the deleted folders and it reports IO error.**

The error was raised in https://github.com/XtremeDevX/turbo-delete/blob/0.0.1/src/main.rs#L114-L120

I'm not familar with rust and the design poupose, but I think we could add a file exist check before these lines.
