### ISSUE TITLE
Question: what make this faster than the builtin window delete? 

### ISSUE THREAD

**Issue by datduyng** [XtremeDevX/turbo-delete#3]
Hi, 

I am very impressed with the tool. This has been a huge productivity gain for me as I previously use ‘rm’ command in powershell and it takes really long some time. I am not a rust programmer but very interested in learning more why is this <400 lines can out perform the window delete command. Would appreciate if you can share any resources you found while solving this problem

Thanks, 

Dominic

**Comment by suptejas** [comment]
Hey!

Would be very happy to explain what we do differently, and it's categorized into multiple different steps:
1) Receive a list of folders in parallel, I use the `jwalk` crate for this one.
2) Sort the list of folders by depth, spawn a threadpool and share it as you go from the highest depth (essentially folders without any subfolders) to the lowest depth.
3) I also realized that there are a few permission issues with folders like `.git`, so I do another directory listing, fix permissions and synchronously delete the left-over files!
